### PR TITLE
workspace class

### PR DESCRIPTION
**Pull request by amereghe**
This PR aims at replacing the `studyFactory` class with the `workspace` class. The new class is meant to be a parent class where the management of studies should be performed. No new functionality has been added. All the interfaces have been changed, for having (hopefully) more sensible names. Logging and checking flags have been added to the interfaces.

The `README.md` has been updated accrodingly.

Other minor changes:
   * `pySixDeskAbsPath`, containing the full path to `pySixDesk`, added to `utils.py` module, such that it can be used anywhere;
   * python 3.6.8 reported in `README.md` file; recommendations on setting up the lxplus environment changed accordingly;

### CODE REVIEW

**Comment by luxiaohan** [comment]
Hi Alessio, 
     Thanks for the work. I have took a look through the modifications. It's more readable.
     I just have two minor comments:
     1. There are some changes and new features in the ```WorkSpace``` class, do you test the code? or I can test it later. 
     2. I noticed that you use the different conventions to name the variables and methods, I think we should unify the naming conventions. e.g. you used the camel-case (mixedCase) to name the methods, but  it's not recommended in the [PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) . It's not a big deal, but I think It will be better to use the unified naming conventions. How do you think?
Cheers,
Xiaohan

**Comment by amereghe** [comment]
Hi Xiaohan,
thanks for the feedback. Here the replies:

1. yes I have tested the new code up to MADX job submission - it should be enough. If you want to cross-check, more than welcome!
1. good point - let's follow PEP8. I will make the modifications and update the PR.

Cheers,
A.

**Comment by amereghe** [comment]
ok - code should be compliant to PEP8 recommendations

**Comment by amereghe** [comment]
Rock & Roll :P

**Pull request merged**
