### PR TITLE
fixes to db types

### PR DESCRIPTION
**Pull request by loiccoyle**
This PR removes the `utils.evlt` function and changes all the function in `utils.py` which used to return a status variable to raise exceptions instead. The calls to these function have been wrapped in try/except when necessary.

There are also some fixes to the db types, notably `study.madx_params` were previously only set to INTs this is now fixed, and added a check for BIGINTs.

Also, it adds control over the jobFlavour for htcondor, as I think the preprocess job should be ran in the 'espresso' queue, as it is quite a short job.

### CODE REVIEW

**Comment by luxiaohan** [comment]
Thanks for the works.
But I think we already discussed the potential modification about `status`. Let's do it later~

**Comment by loiccoyle** [comment]
I reverted the changes to the `status` returning `utils.py` functions, even though I think changing from `status` variables to raising exceptions should be done sooner rather than later.

**Comment by loiccoyle** [comment]
Can this be merged? Once it is, I will submit a separate PR to fix the tests.

**Comment by luxiaohan** [comment]
Sorry for the late reply. I just look through the chages, It can be merged. 
And when will you be around today. We could continue the discussion about the last PR.

**Comment by loiccoyle** [comment]
I can come by this afternoon, around 3pm ?

**Comment by luxiaohan** [comment]
Ok, perfect.

**Pull request merged**
